dataset: 
    mode: basic # str: ['basic', 'lmdb', 'dali'] (dali mode is under development)
    train_csv_path: data/trans-train.csv # str: must change for your case
    train_image_path: data/images/train/ # str: option for basic or dali mode
    lmdb_path: data/test-lmdb # str: option for lmdb mode
    validation:
        mode: auto # str: ['auto', 'manual']
        nfold: 5 # currently use 1~n-1 fold for train, n fold for validate
dataloader:
    batch_size: 64
    data_augment:
        mode: yaml # str: ['yaml', 'custom']
        lib: torchvision # str: ['torchvision', 'albumentations']
        train_trans:
            - name: Resize
              params: {'size': [224,224]}
            - name: RandomHorizontalFlip
              params: {}
            - name: ToTensor
              params: {}
            - name: Normalize
              params: {'mean': [0.5, 0.5, 0.5], 'std': [0.5, 0.5, 0.5]}
        valid_trans:
            - name: Resize
              params: {'size': [224,224]}
            - name: ToTensor
              params: {}
            - name: Normalize
              params: {'mean': [0.5, 0.5, 0.5], 'std': [0.5, 0.5, 0.5]}
model:
    model_name: resnet18
    image_size: [3, 256, 256] # [C, H, W]
    num_classes: 120
    pretrained: True
    dataparallel: True
amp:
    use_amp: True
    opt_level: O1
optimizer:
    opt_name: SGD
    opt_params:
        lr: 0.1
        momentum: 0.9
        dampening: 0.0
        weight_decay: 0.0005
        nesterov: True
loss:
    loss_name: CrossEntropyLoss
    loss_params: {}
train:
    epoch: 20
log:
    log_dir: logs/test 
    save_name: test 
    save_interval: 2
    save_final: True
    save_best_val: True
    save_skip_epoch: 10

    



