dataset: 
    train_image_path: data/images/train/ # str: must change for your case
    test_image_path: data/images/test/ # str: must change for your case
    train_csv_path: data/trans-train.csv # str: must change for your case
    test_csv_path: data/test.csv # str: must change for your case
    validation:
        mode: auto # str: ['auto', 'manual']
        nfold: 5 # currently use 1~n-1 fold for train, n fold for validate
dataloader:
    batch_size: 64
model:
    model_name: resnet18
    image_size: 256
    channel_size: 3
    num_classes: 120
    pretrained: True
    dataparallel: True
optimizer:
    opt_name: sgd
    opt_params:
        lr: 0.1
        momentum: 0.9
        dampening: 0.0
        weight_decay: 0.0005
        nesterov: True
loss:
    loss_name: CrossEntropyLoss
    loss_params:
        dummy: dummy
train:
    epoch: 20
amp:
    use_amp: True
    opt_level: O1



