dataset: 
    train_image_path: ../data/images/train/
    test_image_path: ../data/images/test/
    train_csv_path: ../data/trans-train.csv
    test_csv_path: ../data/test.csv
dataloader:
    batch_size: 64

